# Generated by Django 4.0.6 on 2022-08-02 15:27

import E_learn_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_learn_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', E_learn_app.models.UserManager()),
            ],
        ),
    ]
